Dev
agas0077/mesto4withServer pull request #2
Opened 2020-04-18 22:58 UTC by agas0077

Сделал все задания 13 проектной работы

2020-04-19 18:06 UTC, aarefiev requested changes
Хорошая работа. :+1: Выполнено дополнительное задание :+1: :+1: :+1: .

Хорошее описание проекта, но не хватает инструкции о том как его развернуть. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели) :book: . Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается с ошибками. Отдельного конфигурационный файл со всеми настройками для работы сервера не обнаружено. Схемы моделей настроены корректно, но кроме полей формата `URL`. Роуты в большинстве настроены согласно заданию, есть ошибки в кодах ответов при нештаных ситуациях. Централизованная обработка несуществующего роута есть, работает. Сервер локально запускается в режиме хот-релоада и без, ошибок в консоли не возникает. Временные файлы игнорируются, но файл конфигурации для Visual Studio Code пропущен.

Краткий список ошибок и улучшений представлен ниже, расширенные комментарии непосредственно в коде.

**Нужно исправить:**
1. Ошибка в `.editorconfig`.
2. Не игнорируется файл конфигурации IDE.
3. Ошибки линтинга.
4. Некорректная схема поля.
5. При возникновении ошибки при получении пользователя по `id` всегда возвращается 404.
6. При возникновении ошибки при получении пользователей всегда возвращается 404.
7. При возникновении ошибки при обновлении аватара пользователя всегда возвращается 404.
8. При попытке поставить лайк на карточку по `id`, который не существует, возвращается 200.
9. При попытке удалить лайк с карточки по `id`, который не существует, возвращается 200.
10. При попытке удалить карточку по `id`, который не существует, возвращается 200.
11. При возникновении ошибки при получении карточек всегда возвращается 404.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. Не задавать CORS для ресурсов на одном домене.
3. Удалять неиспользуемый код.

2020-04-19 18:06 UTC, aarefiev commented on .editorconfig
> +}
Нужно исправить: ошибка в `.editorconfig`.
Судя по всему сюда случайно попала конфигурация `.eslint`.

2020-04-19 18:06 UTC, aarefiev commented on .vscode/launch.json
>                  "<node_internals>/**"
Нужно исправить: не игнорируется файл конфигурации IDE.
Этот файл поддерживается только Visual Studio Code, для других IDE этот файл никак не будет обработан. Но, все современные IDE умеют работать с `.editorconfig`.

2020-04-19 18:06 UTC, aarefiev commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Если оставить определение значений в коде, то возникает несколько очевидных проблем:
- изменение какой-то настройки требует изменений всех файлов, где она используется,
- нельзя использовать отдельные настройки для разработки и продакшена

Лучше создать отдельный файл (например, `config.js`) и в нём уже заполнять те настройки, которые будут использоваться в проекте (например, секретный ключ, порт сервера или адрес для подключения к базе данных). Далее этот файл подключать в тех файлах, где необходимо получить значения. Пример файла:
```js
module.exports.PORT = process.env.PORT || 3000;
module.exports.DATABASE_URL = 'mongodb://localhost:27017/mestodb';
```

2020-04-19 18:06 UTC, aarefiev commented on controllers/cards.js
> +module.exports.deleteCard = (req, res) => {
Нужно исправить: ошибки линтинга.

При попытке запустить команду линтинга `npx eslint --ext .js .` линтер сообщает об ошибках:
```bash
$ npx eslint --ext .js .
/home/jmi/work/ya-reviews/mesto4withServer/routes/cards.js
  27:1   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  27:43  error  Unexpected use of comma operator                                       no-sequences

✖ 2 problems (2 errors, 0 warnings)
```

Ожидаемый результат - ошибок маркированных **error** нет (**warning** допускается).

2020-04-19 18:06 UTC, aarefiev commented on app.js
> +});
Можно лучше: не задавать CORS для ресурсов на одном домене.
CORS нужен только тогда, когда требуется из JavaScript сделать запрос на ресурс, который доступен на другом домене. В противном случае браузер просто не будет делать запрос с методом OPTIONS.

2020-04-19 18:06 UTC, aarefiev commented on models/users.js
> +  },
Нужно исправить: некорректная схема поля.
Согласно заданию:
`avatar` - это строка формата `URL`, обязательное поле.

Для валидации можно использовать модуль: https://www.npmjs.com/package/validator .
Нужный метод: `.isURL`.

2020-04-19 18:06 UTC, aarefiev commented on models/cards.js
> +  },
Нужно исправить: некорректная схема поля.
Согласно заданию:
`link` - это строка формата `URL`, обязательное поле.

2020-04-19 18:06 UTC, aarefiev commented on controllers/users.js
> +    });
Нужно исправить: при возникновении ошибки при получении пользователя по `id` всегда возвращается 404.
Библиотека `mongoose` работает с идентификаторами определенного формата. Это должна быть цифробуквенная строка размером в 24 символа. Когда в качестве `id` передана строка другого формата будет брошено исключение:
```
'Cast to ObjectId failed for value "1" at path "_id" for model "user"'
```
В этом случае нужно возвращать [500 Internal Server Error](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/500).

В случае если не была найдена запись, то нужно возвращать [404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404).

То есть:
- запрос `GET /users/1` - ответ с кодом 500,
- запрос `GET /users/5e9c8aceedad0c4d24328bb7` - ответ с кодом 404 (передал корректный `id`, но такой, чтобы не было в базе данных)

2020-04-19 18:06 UTC, aarefiev commented on controllers/users.js
> +    });
Нужно исправить: при возникновении ошибки при получении пользователей всегда возвращается 404.
Тоже самое, что и при получении пользователя.

2020-04-19 18:06 UTC, aarefiev commented on controllers/users.js
> +    });
Нужно исправить: при возникновении ошибки при получении пользователя всегда возвращается 404.

2020-04-19 18:06 UTC, aarefiev commented on controllers/users.js
> +    });
Нужно исправить: при возникновении ошибки при обновлении аватара пользователя всегда возвращается 404.
Ну тут вообще непонятно почему 404 в `req.user._id` явно всегда будет корректный идентификатор и этот идентификатор всегда будет в базе данных. Конечно, если пользователя удалят до того, как он обновит страницу. Но тут уже вопрос в том, как закрывать ресурсы на доступ, а это уже другая история и будет рассматриваться в следующей практике.

2020-04-19 18:06 UTC, aarefiev commented on controllers/cards.js
> +    })
Нужно исправить: при попытке поставить лайк на карточку по `id`, который не существует, возвращается 200.
Запрос: `PUT /cards/5e9b0f078c01027932cfc097/likes`.
Ответ с кодом 200:
```json
{}
```
Ожидается ответ с кодом [404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404).

2020-04-19 18:06 UTC, aarefiev commented on controllers/cards.js
> +    })
Нужно исправить: при попытке удалить лайк с карточки по `id`, который не существует, возвращается 200.
Запрос: `DELETE /cards/5e9b0f078c01027932cfc097/likes`.
Ответ с кодом 200:
```json
{}
```
Ожидается ответ с кодом [404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404).

2020-04-19 18:06 UTC, aarefiev commented on controllers/cards.js
> +    })
Нужно исправить: при попытке удалить карточку по `id`, который не существует, возвращается 200.
Запрос: `DELETE /cards/5e9b0f078c01027932cfc097`.
Ответ с кодом 200:
```json
{}
```
Ожидается ответ с кодом [404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404).

2020-04-19 18:06 UTC, aarefiev commented on controllers/cards.js
> +    });
Нужно исправить: при возникновении ошибки при получении карточек всегда возвращается 404.
Тоже самое, что и при получении пользователя.

2020-04-19 18:06 UTC, aarefiev commented on routes/cards.js
> +// };
Можно лучше: удалять неиспользуемый код.

2020-04-19 18:49 UTC, agas0077 commented on .editorconfig
> +}
Исправил

2020-04-19 18:51 UTC, agas0077 commented on .vscode/launch.json
>                  "<node_internals>/**"
Исправил

2020-04-19 18:57 UTC, agas0077 commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Исправил

2020-04-19 19:05 UTC, agas0077 commented on controllers/cards.js
> +module.exports.deleteCard = (req, res) => {
Вроде исправил, но у меня при этой команде выдается список флагов 
![image](https://user-images.githubusercontent.com/61889096/79697162-d55d1880-8289-11ea-8901-9e930474ddef.png)

2020-04-19 19:06 UTC, agas0077 commented on app.js
> +});
Использовал для проверки работы через фронтенд. Удалил.

2020-04-19 19:20 UTC, agas0077 commented on models/users.js
> +  },
Исправил

2020-04-19 19:21 UTC, agas0077 commented on models/cards.js
> +  },
Исправил

2020-04-19 19:40 UTC, agas0077 commented on controllers/users.js
> +    });
Исправил

2020-04-19 19:44 UTC, agas0077 commented on controllers/users.js
> +    });
Не совсем понял. Тут же есть только два исходных варианта: либо по адресу есть массив пользователей, либо его нет. Исправил на 500

2020-04-19 19:45 UTC, agas0077 commented on controllers/users.js
> +    });
Исправил

2020-04-19 19:47 UTC, agas0077 commented on controllers/users.js
> +    });
Исправил

2020-04-19 20:03 UTC, agas0077 commented on controllers/cards.js
> +    })
Исправил

2020-04-19 20:17 UTC, agas0077 commented on controllers/cards.js
> +    })
Исправил

2020-04-19 20:22 UTC, agas0077 commented on controllers/cards.js
> +    })
Исправил

2020-04-19 20:24 UTC, agas0077 commented on controllers/cards.js
> +    });
Не совсем понял. Тут же есть только два исходных варианта: либо по адресу есть массив карточек, либо его нет. Никакого id не передается. Исправил на 500

2020-04-20 17:37 UTC, aarefiev commented on controllers/cards.js
> +module.exports.deleteCard = (req, res) => {
Судя по скрину, команда не была введена полностью. После указания списка расширений (т.е `--ext .js`) должен идти путь до директории (если в текущей директории, то можно передавать точку). Корректная команда:
```bash
$ npx eslint --ext .js .
```

2020-04-20 17:38 UTC, aarefiev commented on controllers/users.js
> +    });
Я про то, что по-умолчанию 500 ошибка.

2020-04-20 17:38 UTC, aarefiev commented on controllers/cards.js
> +    });
Я про то, что по-умолчанию 500 ошибка.

2020-04-20 18:27 UTC, aarefiev requested changes
Отлично, стало намного лучше. Есть ещё вопросы по обработке нештатных ситуаций и `HTTP` кодам ответов на них.

**Нужно исправить:**
1. Ошибка в конфигурации линтера.
2. При возникновении ошибки при удалении карточки всегда возвращается 404.
3. При возникновении ошибки при установке лайка на карточку всегда возвращается 404.
4. При возникновении ошибки при удалении лайка с карточки всегда возвращается 404.
5. При попытке получить пользователя с невалидным `id` возвращается 404, а с валидным 200.
6. При обновлении профиля не выполняется валидация на уровне модели.

**Можно лучше:** использовать метод `findByIdAndDelete`.

2020-04-20 18:27 UTC, aarefiev commented on .eslintrc.json
> +  }
Нужно исправить: ошибка в конфигурации линтера.
Конфигурация не совсем верна:
```bash
$ npx eslint --ext .js .
.eslintrc.json:
	Configuration for rule "allow" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"_id"').

```

2020-04-20 18:27 UTC, aarefiev commented on controllers/cards.js
> +    });
Нужно исправить: при возникновении ошибки при удалении карточки всегда возвращается 404.
По-умолчанию ожидается 500 Internal Server Error:
- обработка ситуации, когда передан невалидный `id`,
- любые другие ошибки (например, `TypeError` или `SyntaxError`).
В случае если `id` валидный, а запись с таким `id` не найдена в базе дынных нужно возвращать 404 Not Found.

2020-04-20 18:27 UTC, aarefiev commented on controllers/cards.js
> +      }
Можно лучше: использовать метод `findByIdAndDelete`.
Метод возвращает запись из базы даных в формате JSON, либо `null`, если карточка не найдена в базе данных.
В этом случае проверять проще:
```suggestion
      if (!card) return res.status(404).send({ 'Карточка не найдена' });
      res.status(200).send(card);
```

2020-04-20 18:27 UTC, aarefiev commented on controllers/cards.js
> +    });
Нужно исправить: при возникновении ошибки при установке лайка на карточку всегда возвращается 404.
По-умолчанию ожидается 500 Internal Server Error.

2020-04-20 18:27 UTC, aarefiev commented on controllers/cards.js
> +    });
Нужно исправить: при возникновении ошибки при удалении лайка с карточки всегда возвращается 404.
По-умолчанию ожидается 500 Internal Server Error.

2020-04-20 18:27 UTC, aarefiev commented on controllers/users.js
> +      }
Нужно исправить: при попытке получить пользователя с невалидным `id` возвращается 404, а с валидным 200.
**Невалидный `id`**:
Запрос  `GET /users/5e9c8aceedad0c4d2432_bb8`
Ответ с кодом 404:
```json
{
    "message": "Запрашиваемый пользователь не найден"
}
```
**Валидный `id`**:
Запрос `GET /users/5e9c8aceedad0c4d24328bb8`
Ответ с кодом 200:
```json
{}
```

Во первых, регулярное выражение `\w` эквивалентно `[A-Za-z0-0_]`, те пропускает не только буквы и цифры, а также нижнее подчеркивание. А с таким `id` `mongoose` не может работать:
```
'Cast to ObjectId failed for value "5e9b2988b9b9280dc5db6_92" at path "_id" for model "user"'
``` 
Во вторых, если происходит ошибка на сервере, то это 500.
В третьих, проверку идентификатора на формат после того как сам запрос уже был выполнен это неправильно. Сначала проверяем данные, потом делаем запрос - про это будет отдельная работа.

Отправку 404 нужно вынести в `.then()` блок, когда запись будет не найдена `user` будет равен `null`.

2020-04-20 18:27 UTC, aarefiev commented on controllers/users.js
> +      }
Нужно исправить: при попытке получить пользователя с невалидным `id` возвращается 404, а с валидным 200.
Аналогично комментарию для `getUser`

2020-04-20 18:27 UTC, aarefiev commented on controllers/users.js
> +  )
Нужно исправить: при обновлении профиля не выполняется валидация на уровне модели.
Эту ошибку я пропустил в прошлый раз.

В общем суть такова, что `mongoose` по-умолчанию при выполнении UPDATE операций не выполняет валидацию. Например, можно сделать запрос `PATCH /users/me` и передать пустое тело запроса. Будет получен ответ с кодом 200 и с пустым телом. Хотя, если бы была включена валидация, то было брошено исключение и был бы получен ответ с кодом 500.

Подробнее: https://mongoosejs.com/docs/validation.html#update-validators .

2020-04-20 18:27 UTC, aarefiev commented on controllers/users.js
> +  )
Нужно исправить: при обновлении профиля не выполняется валидация на уровне модели.
Эту ошибку я пропустил в прошлый раз.
Аналогично комментарию для `updateAvatar`.

2020-04-21 08:46 UTC, agas0077 commented on controllers/cards.js
> +module.exports.deleteCard = (req, res) => {
Спасибо, исправил

2020-04-21 09:14 UTC, agas0077 commented on .eslintrc.json
> +  }
исправил

2020-04-21 19:50 UTC, agas0077 commented on controllers/cards.js
> +    });
Исправил

2020-04-21 19:55 UTC, agas0077 commented on controllers/cards.js
> +      }
Исправил

2020-04-21 19:57 UTC, agas0077 commented on controllers/cards.js
> +    });
Исправил

2020-04-21 20:19 UTC, agas0077 commented on controllers/cards.js
> +    });
Исправил

2020-04-21 20:25 UTC, agas0077 commented on controllers/users.js
> +      }
Исправил по аналогии с лайками и удалением карточек

2020-04-21 20:29 UTC, agas0077 commented on controllers/users.js
> +      }
Исправил

2020-04-21 20:44 UTC, agas0077 commented on controllers/users.js
> +  )
Исправил

2020-04-21 20:47 UTC, agas0077 commented on controllers/users.js
> +  )
Исправил

2020-04-23 05:55 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены. Новых не обнаружено. Работа принимается :rocket: .
Добавил информации о том как лучше всего обрабатывать несущетсвующие записи. Такой подход (с модулями ошибок) пригодится позже.

**Можно лучше:**
1. Выключать правила `eslint` точечно.
2. Использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-23 05:55 UTC, aarefiev commented on .eslintrc
> +  }
Можно лучше: выключать правила `eslint` точечно.
Сейчас правило полностью блокируется. Это плохо, потому что возможно именование переменных с нижним подчеркиванием везде, даже там, где без этого можно обойтись. Лучше так:
```suggestion
  "rules": {
    "no-underscore-dangle": ["error", { "allow": ["_id"] }]
  }
```

2020-04-23 05:55 UTC, aarefiev commented on controllers/cards.js
> +    })
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
В `mongoose` по-умолчанию методы, которые делают выборку значений из базы данных по какому-то условию, возвращают `null` в случае отсутствия записи в базе данных. Для того, чтобы отловить эту ситуацию есть хелпер [`.orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail).

Хелпер принимает функцию, которая выполняет _reject_ промиса. Если функция будет возвращать какое-то значение, оно будет передано в `.catch()` блок, если нет, то будет отправлено значение по-умолчанию.

Но это не всё. Ещё нужно корректно прокинуть код ошибки. Так как внутри `orFail()` хелпера можно передать любое значение, то я рекомендую создать отдельный модуль для ошибки. Модуль будет содержать класс, который наследует класс `Error` добавляя туда свойство, в котором будет определен HTTP код ошибки. Например для 404 он будет выглядеть так:
```js
// errors/notFoundError.js
class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```

Далее отправка ошибки в `orFail()` сводится к следующему:
```js
.orFail(() => new NotFoundError('Карточка не найдена'))
```

А передача кода уходит в `.catch()` блок:
```js
.catch((err) => res.status(err.statusCode || 500).send({ message: 'Что-то пошло не так', err: err.message }));
```

2020-04-23 05:55 UTC, aarefiev commented on controllers/cards.js
> +    })
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-23 05:55 UTC, aarefiev commented on controllers/users.js
> +    })
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-23 05:55 UTC, aarefiev commented on controllers/users.js
> +    })
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-04-29 18:55 UTC, agas0077 commented on controllers/cards.js
> +    })
Спасибо! Все реализовал.

2020-04-29 18:55 UTC, merged