Dev
agas0077/mesto4withServer pull request #6
Opened 2020-05-17 16:26 UTC by agas0077

2020-05-17 18:30 UTC, aarefiev requested changes
Хорошая работа. Реализовано дополнительное задание :+1: .

Есть хорошо оформленное описание проекта. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели, мидлвары, модули ошибок). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибок. Для роутов назначена валидация согласно заданию. Есть ошибки в схемах. Централизованный обработчик ошибок реализован, работает. Обработчик несуществующего роута реализован, работает. Мидлвара авторизации реализована, работает. Запросы логируются в `request.log`, ошибки в `error.log`. Временные файлы игнорируются. Сервер локально запускается с хот релоадом и без. Работу публичного сервера проверить не удалось, по причине отсутствия сервера. Сертификат валиден. Секретный ключ на публичном сервере проверить не удалось. Автоматическое восстановление работоспособности при обращении на роут краш-теста проверить не удалось.

Ниже краткий список ошибок и улучшений, развернутые комментарии непосредственно в коде.

**Нужно исправить:**
1. Невозможно подключиться к публичному серверу.
2. Ошибка в схеме валидации роута.
3. При создании карточки возвращается 500.

**Можно лучше:**
1. Обработчик ошибок должен быть последним обработчиком.
2. Указать адрес для подключения к базе данных полностью.
3. Вынести секретный ключ в конфигурационный файл.
4. Использовать метод `.uri()` для валидации строк формата `URL`.

2020-05-17 18:30 UTC, aarefiev commented on config.js
> +module.exports.DATABASE_URL = DB_PASSWORD ? `mongodb://DND:${DB_PASSWORD}@dnd-shard-00-00-yxink.azure.mongodb.net:27017,dnd-shard-00-01-yxink.azure.mongodb.net:27017,dnd-shard-00-02-yxink.azure.mongo
Можно лучше: указать адрес для подключения к базе данных полностью.
Так как пароль можно передавать вместе с адресом, тогда можно адрес для подключения к БД полность указать в `.env`. Тогда в кнфиге будет:
```suggestion
module.exports.DATABASE_URL = process.env.DATABASE_URL || 'mongodb://localhost:27017/mydb';
```

Либо есть для продакшена то:
```suggestion
const isProduction = process.env.NODE_ENV === 'production';

module.exports.DATABASE_URL = isProduction ? process.env.DATABASE_URL : 'mongodb://localhost:27017/mydb';
```

2020-05-17 18:30 UTC, aarefiev commented on app.js
>    celebrate({
Нужно исправить: ошибка в схеме валидации роута.
Где:
https://github.com/agas0077/mesto4withServer/blob/61c1c2359c34e206ec0ed9f341205266cb844205/app.js#L43
https://github.com/agas0077/mesto4withServer/blob/61c1c2359c34e206ec0ed9f341205266cb844205/app.js#L47
https://github.com/agas0077/mesto4withServer/blob/61c1c2359c34e206ec0ed9f341205266cb844205/app.js#L57

По заданию:
- `email` - строка, формат `email`, обязательное поле,
- `avatar` - строка, формат `URL`, обязательное поле

2020-05-17 18:30 UTC, aarefiev commented on routes/cards.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
Можно лучше: использовать метод `.uri()` для валидации строк формата `URL`.
https://github.com/hapijs/joi/blob/master/API.md#stringurioptions

2020-05-17 18:30 UTC, aarefiev commented on routes/users.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
Можно лучше: использовать метод `.uri()` для валидации строк формата `URL`.

2020-05-17 18:30 UTC, aarefiev commented on routes/cards.js
>  cards.post(
Нужно исправить: при создании карточки возвращается 500.
Судя по всему, что бросается исключение.
https://github.com/agas0077/mesto4withServer/blob/61c1c2359c34e206ec0ed9f341205266cb844205/controllers/cards.js#L21-L22

2020-05-17 18:30 UTC, aarefiev commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
Нужно исправить: невозможно подключиться к публичному серверу.
При обращении на `https://api.mesto4.fun/signup` получаю ответ:
```html
<html>

<head>
	<title>502 Bad Gateway</title>
</head>

<body bgcolor="white">
	<center>
		<h1>502 Bad Gateway</h1>
	</center>
	<hr>
	<center>nginx/1.14.0 (Ubuntu)</center>
</body>

</html>
```

А по IP: `http://130.193.38.158/signup`:
```html
<html>

<head>
	<title>404 Not Found</title>
</head>

<body bgcolor="white">
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx/1.14.0 (Ubuntu)</center>
</body>

</html>
```

2020-05-17 18:30 UTC, aarefiev commented on middlewares/auth.js
>      payload = jwt.verify(token, NODE_ENV === 'production' ? JWT_SECRET : 'SOME-SECRET-KEY');
Можно лучше: вынести секретный ключ в конфигурационный файл.
По аналогии с адресом для подключения к БД. Секретный ключ можно определить в конфигурационном файле:
```js
// config.js
const isProduction = NODE_ENV === 'production';

module.exports.JWT_SECRET = isProduction ? JWT_SECRET : 'SOME-SECRET-KEY';
```

2020-05-17 18:30 UTC, aarefiev commented on middlewares/auth.js
>      payload = jwt.verify(token, NODE_ENV === 'production' ? JWT_SECRET : 'SOME-SECRET-KEY');
И здесь:
https://github.com/agas0077/mesto4withServer/blob/61c1c2359c34e206ec0ed9f341205266cb844205/controllers/credentials.js#L40

2020-05-17 18:30 UTC, aarefiev commented on app.js
>  });
Можно лучше: обработчик ошибок должен быть последним обработчиком.
Это связано с тем, что ответ уже будет отправлен клиенту и если следующий обработчик вызовет её повторно, то произойдёт ошибка.

2020-05-18 08:12 UTC, agas0077 commented on config.js
> +module.exports.DATABASE_URL = DB_PASSWORD ? `mongodb://DND:${DB_PASSWORD}@dnd-shard-00-00-yxink.azure.mongodb.net:27017,dnd-shard-00-01-yxink.azure.mongodb.net:27017,dnd-shard-00-02-yxink.azure.mongo
Исправил

2020-05-18 08:16 UTC, agas0077 commented on routes/cards.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
Читал об этом, но в беседе группы писали, что ревьюеры ругаются на этот метод и говорят делать через регулярку...
![image](https://user-images.githubusercontent.com/61889096/82189998-ffd9da00-98f8-11ea-8e06-e6b6e5f9e0ee.png)

2020-05-18 08:19 UTC, agas0077 commented on app.js
>    celebrate({
исправил

2020-05-18 08:19 UTC, agas0077 commented on routes/cards.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
исправил

2020-05-18 08:19 UTC, agas0077 commented on routes/users.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
испрвил

2020-05-18 08:20 UTC, agas0077 commented on routes/cards.js
>  cards.post(
исправил

2020-05-18 08:25 UTC, agas0077 commented on middlewares/auth.js
>      payload = jwt.verify(token, NODE_ENV === 'production' ? JWT_SECRET : 'SOME-SECRET-KEY');
Исправил

2020-05-18 08:26 UTC, agas0077 commented on app.js
>  });
Исправил

2020-05-18 10:29 UTC, agas0077 commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
Обращение по имени исправил. Но не знаю как исправть обращение к поддомену через IP

2020-05-19 06:43 UTC, aarefiev commented on app.js
>  });
Нужно убрать вызов `next();`, а объявление параметра оставить. Потому что, как вы помните, в _Express_ обработчик ошибок объявляется с 4-я аргументами.

Не забудьте про линтер, он будет ругаться, что объявленная переменная не используется. Здесь нужно выключить правило для строки, где объявляется переменная.

2020-05-19 06:48 UTC, aarefiev commented on routes/cards.js
> +        .regex(/(https?:\/\/)(www\.)?((\w+\.\w{2,})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))(:\d{2,5})?.*#?/i),
Да и этому есть объяснение: https://github.com/hapijs/joi/issues/1732

2020-05-19 07:13 UTC, aarefiev requested changes
Удалось проверить публичный сервер, но этот вопрос ещё решён не полностью.

**Нужно исправить:**
1. Невозможно подключиться к публичному серверу по IP и протоколу HTTP.
2. На публичном сервере используется тот же самый секретный ключ, что и локально.

**Можно лучше:** можно упростить.

2020-05-19 07:13 UTC, aarefiev commented on routes/users.js
Можно лучше: можно упростить.
Где:
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/users.js#L13-L14
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/users.js#L22-L23
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/users.js#L52-L53
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/cards.js#L10-L11
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/cards.js#L22-L23
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/cards.js#L37-L38
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/cards.js#L53-L54
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/cards.js#L67-L68

В этих случаях достаточно доверять _Mongoose_. Считаем, что если удалось создать или обновить запись, то возвращаемое значение будет точно не `null`. Если же `null`, то его поймает хелпер `.orFail()`. В остальных нештатных ситуациях будет брошено исключение и оно уже сразу попадёт в обработку `.catch()`. 

Поэтому стоит в этих местах убрать проверку на существование и бросание исключения.

2020-05-19 07:13 UTC, aarefiev commented on routes/users.js
Можно лучше: можно упростить:
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/users.js#L31-L43
https://github.com/agas0077/mesto4withServer/blob/dev/controllers/users.js#L59-L71

При обновлении профиля мы знаем, что пользователь есть, так как он авторизовался по токену. В реальной системе, токен кроме валидности проверяется ещё на актуальность. Например, пользователь может быть удалён, в этом случае токен, который был выдан ему ранее должен стать недействительным. 

Чтобы это реализовать, достаточно в `auth.js` производить проверку на существование пользователя в базе. После того как по токену был получен `id`.
Эта проверка будет гарантировать нам, что авторизованный пользователь есть в базе и при обновлении профиля нам не нужно будет проверять на `null` и бросать исключение.

2020-05-19 07:13 UTC, aarefiev commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
Нужно исправить: невозможно подключиться к публичному серверу по IP и протоколу HTTP.
Ответ:
```html
<html>

<head>
	<title>404 Not Found</title>
</head>

<body bgcolor="white">
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx/1.14.0 (Ubuntu)</center>
</body>

</html>
```

По HTTPS + домен всё работает. Судя по всему на сервере выключено подключение по HTTP.

2020-05-19 07:13 UTC, aarefiev commented on config.js
> +module.exports.KEY = isProduction ? process.env.JWT_SECRET : 'SOME-SECRET-KEY';
Нужно исправить: на публичном сервере используется тот же самый секретный ключ, что и локально.
Можно воспроизвести в Postman. Для этого нужно создать куку для публичного сервера с значением куки `jwt`, полученной локально. И после этого перейти на закрытый роут на публичном сервере. Например, при обращении на `/users` будет выведено следующее:
```json
[
    {
        "_id": "5ec25adfb4912354aa5403e3",
        "email": "agas@agas.ru",
        "name": "Andrey",
        "about": "need money",
        "avatar": "https://images.unsplash.com/photo-1558980395-be8a5fcb4251?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60",
        "__v": 0
    }
]
```
Это является одной из дыр в безопасности.
Ожидается, что на сервере будет назначен `JWT_SECRET` через `.env` отличный от `SOME-SECRET-KEY`.
Плюс, проверьте, что назначена `NODE_ENV` с значением `production`.

2020-05-19 12:42 UTC, agas0077 commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
![image](https://user-images.githubusercontent.com/61889096/82327590-4b6ab180-99e7-11ea-8e94-7ae2e6ab2dcb.png)
у меня работает по HTTP. На сервере через certbot включена переадресация c http на https

2020-05-19 12:43 UTC, agas0077 commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
c Ip разбираюсь

2020-05-19 12:45 UTC, agas0077 commented on app.js
>  });
Исправил

2020-05-20 12:21 UTC, agas0077 commented on routes/users.js
Почти везде убрал. Оставил только в тех местах, где были кастомные сообщения

2020-05-20 12:42 UTC, agas0077 commented on config.js
> +module.exports.KEY = isProduction ? process.env.JWT_SECRET : 'SOME-SECRET-KEY';
с сервера почему-то пропал файл env

2020-05-20 14:07 UTC, agas0077 commented on config.js
> +module.exports.KEY = isProduction ? process.env.JWT_SECRET : 'SOME-SECRET-KEY';
Исправил. Должно работать. Если посмотреть через консоль локально без указания NODE_ENV возвращается "SOME_SECRET_KEY", а на сервере уже с указанием NODE_ENV - нормальный ключ

2020-05-21 05:34 UTC, aarefiev requested changes
Публичный сервер стал доступен по IP по протоколу HTTP, но возникла проблема с конфигурацией БД.

**Нужно исправить:** при регистрации на публичном сервере возвращается 500.

**Можно лучше:**
1. Унифицировать ответ.
2. Убрать лишнее.
3. Использовать единый `.catch()` блок для вложенных промисов.
4. Унифицировать ответ для ошибок на сервере.

2020-05-21 05:34 UTC, aarefiev commented on README.md
> +Public IP: 130.193.38.158
Нужно исправить: при регистрации на публичном сервере возвращается 500.
Ответ:
```json
{
    "message": "No write concern mode named 'majority`' found in replica set configuration"
}
```

Актуально по IP и домену по HTTP и по HTTPS.

2020-05-21 05:34 UTC, aarefiev commented on README.md
> +Public IP: 130.193.38.158
Так то: https://stackoverflow.com/questions/57179043/error-while-saving-data-in-mongodb-atlas-with-mongoose/57183151
Но не понятно зачем нужна реплика. Фактически доступ по HTTPS и по HTTP по домену и по IP должен осуществляться к одной и той же БД. Реплику делают, когда с данными работают не пользователи системы, а третьи лица, например, аналитики строят графики или прогнозы.

2020-05-21 05:34 UTC, aarefiev commented on controllers/cards.js
>      .orFail(() => new NotFoundError('Не удалось убрать лайк'))
Можно лучше: унифицировать ответ.
При попытке удалить или поставить лайк на несуществующую карточку возвращается сообщение `'Не удалось найти фотографию с таким id'`. При удалении лайка производится операция обрабтная установке лайка, поэтому есть смысл отправлять аналогичный ответ.

2020-05-21 05:34 UTC, aarefiev commented on controllers/users.js
>    User.findById(id)
Можно лучше: убрать лишнее.
Где: https://github.com/agas0077/mesto4withServer/blob/270f6bc3d4b6958f40c4c92c4dee8eb2814c045f/controllers/users.js#L21
https://github.com/agas0077/mesto4withServer/blob/270f6bc3d4b6958f40c4c92c4dee8eb2814c045f/controllers/users.js#L65
https://github.com/agas0077/mesto4withServer/blob/270f6bc3d4b6958f40c4c92c4dee8eb2814c045f/controllers/cards.js#L10
Аналогично, что и в прошлй раз. Не используется.

2020-05-21 05:34 UTC, aarefiev commented on controllers/cards.js
>          .catch(next);
Можно лучше: использовать единый `.catch()` блок для вложенных промисов.
Особенность работы промисов в том, что `.then()` блоки выполняются в том порядке, в котором они были описаны. Причем вызов следующего `.then()` запускается только после того как промис перейдет в состояние выполнен (_resolved_) или как текущий `.then()` блок будет выполнен. Это означает, что вложенный промис и его `.then()` блоки тоже могут быть встроены в цепочку вызовов, если внутри `.then()` блока будет выполнен `return`.
При наличии одной цепочки вложенный `.catch()` блок можно убирать, потому что любое отклонение промиса (_reject_) будет поймано верхнеуровневым `.catch()` блоком.

2020-05-21 05:34 UTC, aarefiev commented on app.js
>    res.status(err.statusCode || 500).send({ message: err.message });
Можно лучше: унифицировать ответ для ошибок на сервере.
В большинстве случаев клиент не в состоянии поправить ошибку на сервере. Поэтому детали ошибки ему нет смысла отправлять. Обычно детали ошибки логируются на сервере в файл/консоль/менеджер ошибок (типа Sentry, Honeybadger).

Но ответ нужно какой-то отдавать поэтому рекомендую оставить какой-то общий текст. Например: `'Произошла ошибка'`.

```suggestion
  const statusCode = err.statusCode || 500;
  const message = statusCode === 500 ? 'Произошла ошибка' : err.message;
  res.status(statusCode).send({ message });
```

2020-05-21 14:01 UTC, agas0077 commented on README.md
> +Public IP: 130.193.38.158
Если я не ошибаюсь, реплика - это копия базы данных. Не совсем понимаю почему в моем случае это копия. Я просто храню данные не на своем сервере, а в облаке mongoDB Atlas. Там удобнее смотреть записываются данные или нет, чем через shell. 

Ошибку убрал.

2020-05-21 14:03 UTC, agas0077 commented on controllers/users.js
>    User.findById(id)
Ладно( исправил

2020-05-21 14:05 UTC, agas0077 commented on controllers/cards.js
>          .catch(next);
Исправил

2020-05-21 14:08 UTC, agas0077 commented on app.js
>    res.status(err.statusCode || 500).send({ message: err.message });
Исправил

2020-05-21 14:13 UTC, agas0077 commented on controllers/cards.js
>      .orFail(() => new NotFoundError('Не удалось убрать лайк'))
Исправил

2020-05-21 14:47 UTC, aarefiev commented on README.md
> +Public IP: 130.193.38.158
Да, реплика - это ещё одна база данных, которая обычно чуть-чуть отстаёт от _master_. Обновление базы делают на уровне баз данных, не на уровне Node.js. Обычно реплик несколько, с разным отставанием. Суть реплики в том, чтобы избавать _master_ базу от долгих _select_ запросов.

2020-05-21 15:06 UTC, aarefiev requested changes
С секретным ключом всё ещё что-то не то + случайная ошибка.

**Нужно исправить:**
1. На публичном сервере используется тот же ключ, что и локально.
2. Использовать единый `.catch()` блок для вложенных промисов.

2020-05-21 15:06 UTC, aarefiev commented on controllers/cards.js
>      .catch(next);
Нужно исправить: использовать единый `.catch()` блок для вложенных промисов.
Сейчас любой запрос с ошибкой в данных приведёт к тому, что исключение не будет обработано и клиент не получит ответ.
Обработка промисов работает только если дочерний промис возвращается:. Те нужно добавить `return` при выполнении `Card.findOneAndDelete()`.

2020-05-21 15:06 UTC, aarefiev commented on README.md
> +The back-end of project mesto can be accessed from [here](https://api.mesto4.fun "api.mesto4.fun"). __Hopefully avaliable__
Нужно исправить: на публичном сервере используется тот же ключ, что и локально.
Всё-таки с `.env` что-то не то. Нужно убедиться, что он есть и определены все значения, чтобы был определен секретный ключ:
https://github.com/agas0077/mesto4withServer/blob/81e5abc63a10ce25b5209fb916e67a4b76072095/config.js#L8
https://github.com/agas0077/mesto4withServer/blob/81e5abc63a10ce25b5209fb916e67a4b76072095/config.js#L12

После регистрации на публичном сервере была установлена эта кука:
![image](https://user-images.githubusercontent.com/2168159/82572351-42b7de00-9b95-11ea-9084-9bbe55494a6c.png)

С этим ключом можно обратиться к закрытым ресурсам на локальном сервере и наоборот.

2020-05-21 15:23 UTC, agas0077 commented on controllers/cards.js
>      .catch(next);
![image](https://user-images.githubusercontent.com/61889096/82574600-0766e080-9b90-11ea-857b-9e79ea43ebcc.png)

return добавил

2020-05-21 15:51 UTC, agas0077 commented
Не понимаю, почему у вас так получается. У меня, если сначала залогиниться локально, потом вставить куку, полученную локально, для отправки на api.mesto4.fun и попытаться отправить запрос на какой либо рут, который требует авторизации, создаются вот такие логи, и возвращается вот такая ошибка 
![image](https://user-images.githubusercontent.com/61889096/82576972-02eff700-9b93-11ea-96a2-5de5b64657d2.png)
![image](https://user-images.githubusercontent.com/61889096/82577013-0edbb900-9b93-11ea-8e60-89cac129bccd.png)
![image](https://user-images.githubusercontent.com/61889096/82577106-2e72e180-9b93-11ea-814d-02781c83064e.png)
![image](https://user-images.githubusercontent.com/61889096/82577121-33379580-9b93-11ea-864b-2154a9757585.png)
Плюс сделал проверку на то, какой ключ используется .

Первый скрин - удаленный сервер
1 строчка - isProduction 
2 строчка - secret key
![image](https://user-images.githubusercontent.com/61889096/82577360-86114d00-9b93-11ea-8499-c8eee11f01e0.png)

Второй скрин - локальный сервер
![image](https://user-images.githubusercontent.com/61889096/82577324-77c33100-9b93-11ea-9cf9-524f87769adc.png)

2020-05-21 15:58 UTC, agas0077 commented on controllers/cards.js
>      .catch(next);
![image](https://user-images.githubusercontent.com/61889096/82578376-fb315200-9b94-11ea-89db-4dca0da8007f.png)
ESlint исправил вот на такой синтаксис, убрав return. Ошибка возвращается верная.

2020-05-21 18:24 UTC, aarefiev requested changes
Проверил, с ключом на публичном сервере и правда порядок. Я думаю, это была кука с прошлой итерации, когда `.env` файл был утерян. 
В целом всё ок, но я пропустил две ошибки, которые выявляются при детальной проверке. Я уверен, что вы очень быстро с ними справитесь.

**Нужно исправить:**
1. При попытке зайти на закрытые ресурсы с невалидным токеном возвращается 500.
2. Нет роута для тестирования краш теста.

2020-05-21 18:24 UTC, aarefiev commented on middlewares/auth.js
>      next(err);
Нужно исправить: при попытке зайти на закрытые ресурсы с невалидным токеном возвращается 500.
Пропустил эту ошибку. Интересный кейс. 

Такое поведение происходит потому, что при ошибке при верификации токена бросается исключение и оно же сразу и возвращается в обработчик ошибок. В нашей ситуации нужно вернуть 401, поэтому вместо реальной ошибки нужно передать в `next()` новую, которая будет сообщать о том, что не удалось авторизовать.

2020-05-21 18:24 UTC, aarefiev commented on app.js
>    '/signup',
Нужно исправить: нет роута для тестирования краш теста.
Похоже я пропустил и эту ошибку. Но мне показалось, что роут был.
Вообще это является частью задания. См. задание п.8.

2020-05-21 20:01 UTC, agas0077 commented on app.js
>    '/signup',
Он и был, я сам сегодня это заметил, что он исчез, но почему-то в голове была уверенность, что это было задание прошлого спринта

2020-05-21 20:04 UTC, agas0077 commented on middlewares/auth.js
>      next(err);
Тоже видел и обратил внимание, когда искал ошибку с ключом. Но решил не трогать, что бы ничего не сломать. Исправил

2020-05-21 20:04 UTC, agas0077 commented on app.js
>    '/signup',
Исправил

2020-05-21 20:34 UTC, agas0077 commented on app.js
>    '/signup',
Надеюсь с 100 попытки у меня уже получится сдать. Краш тест возвращает ошибку 502 Bad Gateway. Сначала подумал, что это неправильно, ведь должно возвращаться фраза, мы же не зря ее передаем в конструктор. Но потом подумал, что раз она вызывает падение сервера, то никакого ответа ждать не приходится + ошибка правильная, так как если сервер упал, на нужном порте никто ничего не слушает, а значит и 502. Верная логика?

2020-05-22 04:38 UTC, aarefiev commented on middlewares/auth.js
>      next(err);
Отлично.

2020-05-22 04:42 UTC, aarefiev commented on app.js
>    '/signup',
Логика верная. Отдельный код ошибки для этого роута делать не нужно. Этот роут воспроизводит ситуацию, когда сервер в результате запроса упал. В этом случае, сервер должен перезапуститься и работать дальше.

Насчёт сдачи с 100 попытки. Тяжело в учении - легко в бою.

2020-05-22 04:47 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены, новых не обнаружно. Работа принимается :rocket: .

2020-05-22 10:59 UTC, agas0077 commented
Спасибо!

2020-05-22 11:00 UTC, merged